# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vrp.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvrp.proto\"\x9b\x01\n\nVrpRequest\x12\x17\n\x0f\x64istance_matrix\x18\x01 \x03(\x01\x12\x15\n\rnum_locations\x18\x02 \x01(\x05\x12\x14\n\x0cnum_vehicles\x18\x03 \x01(\x05\x12\r\n\x05\x64\x65pot\x18\x04 \x01(\x05\x12\x1c\n\tlocations\x18\x05 \x03(\x0b\x32\t.Location\x12\x1a\n\x08vehicles\x18\x06 \x03(\x0b\x32\x08.Vehicle\"\x8a\x01\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\r\n\x05\x63\x61rgo\x18\x03 \x01(\x05\x12\x16\n\x0eoperation_time\x18\x04 \x01(\x05\x12\x19\n\x11time_window_start\x18\x05 \x01(\x05\x12\x17\n\x0ftime_window_end\x18\x06 \x01(\x05\"D\n\x07Vehicle\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x05\x12\x12\n\nfixed_cost\x18\x02 \x01(\x05\x12\x13\n\x0b\x63ost_per_km\x18\x03 \x01(\x05\"%\n\x0bVrpResponse\x12\x16\n\x06routes\x18\x01 \x03(\x0b\x32\x06.Route\"\x16\n\x05Route\x12\r\n\x05nodes\x18\x01 \x03(\x05\x32\x33\n\nVrpService\x12%\n\x08SolveVrp\x12\x0b.VrpRequest\x1a\x0c.VrpResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vrp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VRPREQUEST']._serialized_start=14
  _globals['_VRPREQUEST']._serialized_end=169
  _globals['_LOCATION']._serialized_start=172
  _globals['_LOCATION']._serialized_end=310
  _globals['_VEHICLE']._serialized_start=312
  _globals['_VEHICLE']._serialized_end=380
  _globals['_VRPRESPONSE']._serialized_start=382
  _globals['_VRPRESPONSE']._serialized_end=419
  _globals['_ROUTE']._serialized_start=421
  _globals['_ROUTE']._serialized_end=443
  _globals['_VRPSERVICE']._serialized_start=445
  _globals['_VRPSERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
